[package]
name = "multiple-pendulum_scheme"
version = "0.1.0"
authors = ["Daiju Nakayama <42.daiju@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
ndarray = "*"
ndarray-linalg = {version = "*", features = ["openblas"]}
